# Generated by Django 5.0.1 on 2024-02-21 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=223)),
                ('address', models.CharField(max_length=223)),
                ('phone', models.CharField(max_length=20)),
                ('second_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_branch', to='accounts.branch'),
        ),
    ]
