# Generated by Django 5.0.1 on 2024-02-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_account_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
