# Generated by Django 5.0.1 on 2024-02-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='second_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
