# Generated by Django 5.0.1 on 2024-02-05 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date_go', models.DateField()),
                ('date_back', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('type_paket', models.CharField(choices=[('Standard', 'Standard'), ('Comfort', 'Comfort'), ('VIP', 'VIP')], default='Standard', max_length=123)),
                ('description', models.TextField()),
                ('current_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=223)),
                ('address', models.CharField(max_length=223)),
                ('phone', models.CharField(max_length=20)),
                ('second_number', models.CharField(max_length=20)),
                ('header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(blank=True, max_length=223, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=22, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='New', max_length=123)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.branch')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=323)),
                ('phone', models.CharField(max_length=22)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('passport_file', models.FileField(blank=True, null=True, upload_to='passports/')),
                ('passport_seria', models.CharField(blank=True, max_length=32, null=True)),
                ('visa_file', models.FileField(blank=True, null=True, upload_to='visas/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_taken', models.PositiveIntegerField(default=0)),
                ('date_payment', models.DateField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('Completed', 'Completed')], default='New', max_length=123)),
                ('last_updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updater', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_owner', to=settings.AUTH_USER_MODEL)),
                ('paket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paket_clients', to='main.tourpaket')),
            ],
        ),
    ]
