# Generated by Django 5.0.1 on 2024-02-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_branchstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
