# Generated by Django 5.0.1 on 2024-02-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpaket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
