# Generated by Django 5.0.1 on 2024-02-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tourpaket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='stay',
            field=models.CharField(max_length=123, null=True),
        ),
    ]
