# Generated by Django 5.0.1 on 2024-02-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_client_country_client_stay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_payment',
            field=models.DateField(null=True),
        ),
    ]
