# Generated by Django 5.0.1 on 2024-02-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_client_date_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passport_date',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_expire',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
