# Generated by Django 5.0.1 on 2024-03-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_client_passport_date_client_passport_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('SendVisa', 'SendVisa'), ('Completed', 'Completed')], default='New', max_length=123),
        ),
    ]
