# Generated by Django 5.0.1 on 2024-03-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_client_description_alter_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('SendVisa', 'SendVisa'), ('Ready', 'Ready'), ('Completed', 'Completed')], default='New', max_length=123),
        ),
    ]
