# Generated by Django 5.0.1 on 2024-03-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='residence',
            field=models.CharField(default='Uzbekistan', max_length=123),
        ),
    ]
